"""initial schema

Revision ID: f1c047bc8f91
Revises: 
Create Date: 2026-05-07 10:19:39.826615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1c047bc8f91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('target_segment', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('segment', sa.String(length=32), nullable=True),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    op.create_index(op.f('ix_companies_segment'), 'companies', ['segment'], unique=False)
    op.create_table('imap_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=128), nullable=False),
    sa.Column('last_uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id')
    )
    op.create_index(op.f('ix_raw_companies_domain'), 'raw_companies', ['domain'], unique=False)
    op.create_index(op.f('ix_raw_companies_inn'), 'raw_companies', ['inn'], unique=False)
    op.create_index(op.f('ix_raw_companies_source'), 'raw_companies', ['source'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('is_role', sa.Boolean(), nullable=False),
    sa.Column('is_free_provider', sa.Boolean(), nullable=False),
    sa.Column('mx_valid', sa.Boolean(), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=False),
    sa.Column('unsubscribed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_emails_company_id'), 'emails', ['company_id'], unique=False)
    op.create_table('sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=True),
    sa.Column('subject_used', sa.String(length=512), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'campaign_id')
    )
    op.create_index(op.f('ix_sends_message_id'), 'sends', ['message_id'], unique=True)
    op.create_index(op.f('ix_sends_status'), 'sends', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sends_status'), table_name='sends')
    op.drop_index(op.f('ix_sends_message_id'), table_name='sends')
    op.drop_table('sends')
    op.drop_index(op.f('ix_emails_company_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_raw_companies_source'), table_name='raw_companies')
    op.drop_index(op.f('ix_raw_companies_inn'), table_name='raw_companies')
    op.drop_index(op.f('ix_raw_companies_domain'), table_name='raw_companies')
    op.drop_table('raw_companies')
    op.drop_table('imap_state')
    op.drop_index(op.f('ix_companies_segment'), table_name='companies')
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
